#!/usr/bin/python


from __future__ import with_statement
import os
import sys
import glob
import unittest
from subprocess import Popen, PIPE


class TestSequenceFunctions(unittest.TestCase):
    def setUp(self):
        self.input = {}
        self.output = {}
        for filename in glob.glob(os.path.join('tests','*.in')):
            with open(filename) as f:
                self.input[filename.rsplit('.')[0]] = self._normalize(f.read())
        for filename in glob.glob(os.path.join('tests','*.out')):
            with open(filename) as f:
                self.output[filename.rsplit('.')[0]] = self._normalize(f.read())
    
    def _normalize(self, value):
        return value.rstrip('\n')
    
    def _test_cmd(self, cmd):
        for test in self.input.keys():
            sys.stdout.write("\nTesting %s with %s" % (cmd[1], test))
            pipe = Popen(cmd, stdin=PIPE, stdout=PIPE, close_fds=True)
            pipe.stdin.write(self.input[test])
            pipe.stdin.close()
            output = self._normalize(pipe.stdout.read())
            self.assertEqual(output, self.output[test])
    
    def test_python(self):
        self._test_cmd(['python', 'csshttprequest.py'])
    
    def test_ruby(self):
        self._test_cmd(['ruby', 'css_http_request.rb'])
    
    def test_php(self):
        self._test_cmd(['php', 'csshttprequest.php'])


if __name__ == '__main__':
    unittest.main()
